version: "3.1"

services:
  rabbit:
    image: rabbitmq:3
    hostname: rabbit.docker
    container_name: dev_rabbit
    ports:
      - "5672:5672"
    networks:
      - backend
    privileged: true

  postgresql:
    image: postgres
    hostname: postgresql.docker
    container_name: dev_postgresql
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: jat
      POSTGRES_DB: jat_db
    networks:
      - backend
    privileged: true

  worker:
    image: worker_image
    hostname: worker_host
    container_name: dev_worker
    build:
      context: worker
      dockerfile: Dockerfile
    volumes:
        - ./worker:/app
    depends_on:
      - postgresql
      - rabbit
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: jat
      POSTGRES_DB: jat_db
      QUEUE_NAME: patents
    networks:
      - backend
    privileged: true
    command: tail -f /dev/null

  api:
    image: api_image
    hostname: api_host
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
        - ./api:/app
    depends_on:
      - postgresql
      - rabbit
    ports:
      - "80:80"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: jat
      POSTGRES_DB: jat_db
      QUEUE_NAME: patents
    networks:
      - backend
    privileged: true
    # Development. It will reload each time src changes
    command: /start-reload.sh

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.178.0.0/16
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.179.0.0/16
